

scrape_configs:
  - job_name: 'baseimages'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']

remote_write:
  - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username: 1221412
      password: glc_eyJvIjoiOTU5NjM2IiwibiI6Im5ld3Rva2VuIiwiayI6InIxN1c5cDVnNExHa0JWWTJ2b0F0MDk5MiIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
